### ISSUE TITLE
Unexpected key: Data, Metadata is expected, but got SqlOptions Error

### ISSUE THREAD

**Issue by enescaglar** [progaudi/progaudi.tarantool#149]
Hi,

When I try to create a table, I am getting the following error but even if the error is thrown when I checked the spaces from tarantool the space is created.

Here is the code I am using (target framework is .net core 3.1) :
`using var tarantoolClient = await Box.Connect("localhost", 3301);
await tarantoolClient.ExecuteSql<string>("CREATE TABLE TEST (ID INT PRIMARY KEY, NAME VARCHAR(200) )");`

> System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Unexpected key: Data, Metadata is expected, but got SqlOptions.)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()

> Inner Exception 1:
ArgumentException: Unexpected key: Data, Metadata is expected, but got SqlOptions.

And this is the result from tarantool command line:

tarantool> box.space.TEST
---
- engine: memtx
  before_replace: 'function: 0x41dcbad0'
  on_replace: 'function: 0x41dcbaa8'
  ck_constraint: []
  field_count: 2
  temporary: false
  index:
    0: &0
      unique: true
      parts:
      - type: integer
        is_nullable: false
        fieldno: 1
      id: 0
      space_id: 516
      type: TREE
      name: pk_unnamed_TEST_1
    pk_unnamed_TEST_1: *0
  is_local: false
  enabled: true
  name: TEST
  id: 516

What am I missing here, what could be the problem?

Thank you.

**Comment by ilnardinio** [comment]
#148

**Comment by enescaglar** [comment]
Thank you for your comment.

**Comment by ilnardinio** [comment]
For quick solution you can see my fork with fix https://github.com/progaudi/progaudi.tarantool/commit/c87f7aa90aadc18c8b915eb32ba4f39188c7dd24

**Comment by enescaglar** [comment]
Thank you, it worked with your fix.

**Comment by AuthenticEshkinKot** [comment]
I've got the same error on INSERT query. Fix created by @ilnardinio solved this issue.
